import { MigrationInterface, QueryRunner } from "typeorm";

export class SyncMissingEntityColumns1787622727935 implements MigrationInterface {
    name = 'SyncMissingEntityColumns1787622727935'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "emergency_contacts" DROP CONSTRAINT "emergency_contacts_patientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "patient_allergies" DROP CONSTRAINT "patient_allergies_patientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "patient_conditions" DROP CONSTRAINT "patient_conditions_patientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "patients_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "doctors_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "beds" DROP CONSTRAINT "beds_wardId_fkey"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "admissions_patientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "admissions_admittingDoctorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "admissions_bedId_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_patientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_doctorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "bills_patientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "bills_admissionId_fkey"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "bills_appointmentId_fkey"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "payments_billId_fkey"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "staff_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "staff_departmentId_fkey"`);
        await queryRunner.query(`ALTER TABLE "lab_tests" DROP CONSTRAINT "lab_tests_patientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "lab_tests" DROP CONSTRAINT "lab_tests_doctorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "medical_records" DROP CONSTRAINT "medical_records_patientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "medical_records" DROP CONSTRAINT "medical_records_doctorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "prescriptions_patientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "prescriptions_doctorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "wards" ADD "currentOccupancy" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "wards" ADD "status" character varying NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "status" character varying NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "wards" DROP COLUMN "floor"`);
        await queryRunner.query(`ALTER TABLE "wards" ADD "floor" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "UQ_e9eac43b40763c55ca076e4d011" UNIQUE ("bedId")`);
        await queryRunner.query(`ALTER TYPE "public"."admissions_status_enum" ADD VALUE 'pending'`);
        await queryRunner.query(`ALTER TYPE "public"."admissions_status_enum" ADD VALUE 'observation'`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "UQ_8681da666ad9699d568b3e91064" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "description" text`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions"  ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions"  ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles"  ("role_id") `);
        await queryRunner.query(`ALTER TABLE "emergency_contacts" ADD CONSTRAINT "FK_093a4f871d059882bbf77fc42f7" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_allergies" ADD CONSTRAINT "FK_6f475d246eec23c35096beb4883" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_conditions" ADD CONSTRAINT "FK_5a6aca46c506997ee2e08568685" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "FK_2c24c3490a26d04b0d70f92057a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "FK_55651e05e46413d510215535edf" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "beds" ADD CONSTRAINT "FK_12c4b045ef8d740bb4fe8051429" FOREIGN KEY ("wardId") REFERENCES "wards"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "FK_f9d5de8d7dd020123a3c76f0a2e" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "FK_d349ad89076dfc329d7aaa9d45d" FOREIGN KEY ("admittingDoctorId") REFERENCES "doctors"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "FK_e9eac43b40763c55ca076e4d011" FOREIGN KEY ("bedId") REFERENCES "beds"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_0c1af27b469cb8dca420c160d65" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "FK_7be8e890fd3e005a757fd71d239" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "FK_8fed00698b025f91dc315888b3a" FOREIGN KEY ("admissionId") REFERENCES "admissions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "FK_d56ac1a3e329bd54022222e0a4f" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_566f88b54bf6a0f477b14e8daa5" FOREIGN KEY ("billId") REFERENCES "bills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_eba76c23bcfc9dad2479b7fd2ad" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_67b6b543fe99f3accd85374f886" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_tests" ADD CONSTRAINT "FK_2d56b760dc15282cf14b05c41b0" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_tests" ADD CONSTRAINT "FK_0756fd06bf80d3e8e16a1f76d43" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_records" ADD CONSTRAINT "FK_7c2c9d4fe663e3330d503bf4407" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_records" ADD CONSTRAINT "FK_fb2a8c47032fe6f18e9266951df" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_51f48335657278b20348dde416c" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_42c70415fad4505386e6d7e9dc4" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_42c70415fad4505386e6d7e9dc4"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_51f48335657278b20348dde416c"`);
        await queryRunner.query(`ALTER TABLE "medical_records" DROP CONSTRAINT "FK_fb2a8c47032fe6f18e9266951df"`);
        await queryRunner.query(`ALTER TABLE "medical_records" DROP CONSTRAINT "FK_7c2c9d4fe663e3330d503bf4407"`);
        await queryRunner.query(`ALTER TABLE "lab_tests" DROP CONSTRAINT "FK_0756fd06bf80d3e8e16a1f76d43"`);
        await queryRunner.query(`ALTER TABLE "lab_tests" DROP CONSTRAINT "FK_2d56b760dc15282cf14b05c41b0"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_67b6b543fe99f3accd85374f886"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_eba76c23bcfc9dad2479b7fd2ad"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_566f88b54bf6a0f477b14e8daa5"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "FK_d56ac1a3e329bd54022222e0a4f"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "FK_8fed00698b025f91dc315888b3a"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "FK_7be8e890fd3e005a757fd71d239"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_0c1af27b469cb8dca420c160d65"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "FK_e9eac43b40763c55ca076e4d011"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "FK_d349ad89076dfc329d7aaa9d45d"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "FK_f9d5de8d7dd020123a3c76f0a2e"`);
        await queryRunner.query(`ALTER TABLE "beds" DROP CONSTRAINT "FK_12c4b045ef8d740bb4fe8051429"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "FK_55651e05e46413d510215535edf"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "FK_2c24c3490a26d04b0d70f92057a"`);
        await queryRunner.query(`ALTER TABLE "patient_conditions" DROP CONSTRAINT "FK_5a6aca46c506997ee2e08568685"`);
        await queryRunner.query(`ALTER TABLE "patient_allergies" DROP CONSTRAINT "FK_6f475d246eec23c35096beb4883"`);
        await queryRunner.query(`ALTER TABLE "emergency_contacts" DROP CONSTRAINT "FK_093a4f871d059882bbf77fc42f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "UQ_8681da666ad9699d568b3e91064"`);
        await queryRunner.query(`CREATE TYPE "public"."admissions_status_enum_old" AS ENUM('admitted', 'discharged', 'transferred', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "admissions" ALTER COLUMN "status" TYPE "public"."admissions_status_enum_old" USING "status"::"text"::"public"."admissions_status_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."admissions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."admissions_status_enum_old" RENAME TO "admissions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "UQ_e9eac43b40763c55ca076e4d011"`);
        await queryRunner.query(`ALTER TABLE "wards" DROP COLUMN "floor"`);
        await queryRunner.query(`ALTER TABLE "wards" ADD "floor" integer`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "wards" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "wards" DROP COLUMN "currentOccupancy"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "prescriptions_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "prescriptions_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "medical_records" ADD CONSTRAINT "medical_records_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "medical_records" ADD CONSTRAINT "medical_records_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lab_tests" ADD CONSTRAINT "lab_tests_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lab_tests" ADD CONSTRAINT "lab_tests_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "staff_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "staff_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "payments_billId_fkey" FOREIGN KEY ("billId") REFERENCES "bills"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "bills_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "bills_admissionId_fkey" FOREIGN KEY ("admissionId") REFERENCES "admissions"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "bills_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "admissions_bedId_fkey" FOREIGN KEY ("bedId") REFERENCES "beds"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "admissions_admittingDoctorId_fkey" FOREIGN KEY ("admittingDoctorId") REFERENCES "doctors"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "admissions_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "beds" ADD CONSTRAINT "beds_wardId_fkey" FOREIGN KEY ("wardId") REFERENCES "wards"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "doctors_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "patients_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "patient_conditions" ADD CONSTRAINT "patient_conditions_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "patient_allergies" ADD CONSTRAINT "patient_allergies_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "emergency_contacts" ADD CONSTRAINT "emergency_contacts_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
